{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.robhogan",
    "module": "noderesolver",
    "version": "0.1.0-alpha.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "noderesolver-0.1.0-alpha.4.jar",
          "url": "noderesolver-0.1.0-alpha.4.jar",
          "size": 6791,
          "sha512": "a5ffb188b6bb71cc3b4d2ae5c27da32835f3c6a74c997db962f1bef480777d759c41c2ca7fef0241661500ec27e6a3b2ec86a844ba1166a373d7c8572904f1e5",
          "sha256": "171da581dc45896cb6aacfdb30036dc726b3387ed44a40568b6fdf2deab10033",
          "sha1": "b7cda057495a4079942d69f7f781349eb0eb7085",
          "md5": "93b08e2467d43262a4640dccec9f78f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "noderesolver-0.1.0-alpha.4.jar",
          "url": "noderesolver-0.1.0-alpha.4.jar",
          "size": 6791,
          "sha512": "a5ffb188b6bb71cc3b4d2ae5c27da32835f3c6a74c997db962f1bef480777d759c41c2ca7fef0241661500ec27e6a3b2ec86a844ba1166a373d7c8572904f1e5",
          "sha256": "171da581dc45896cb6aacfdb30036dc726b3387ed44a40568b6fdf2deab10033",
          "sha1": "b7cda057495a4079942d69f7f781349eb0eb7085",
          "md5": "93b08e2467d43262a4640dccec9f78f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "noderesolver-0.1.0-alpha.4-javadoc.jar",
          "url": "noderesolver-0.1.0-alpha.4-javadoc.jar",
          "size": 261,
          "sha512": "af4fb4698d1b6bdeed0a9b9d871aae0193a163b1e0ecda990eae7a3a0973ac0d306a7eb4c5f149f0bd4ae5bb6f3ff9821d01be0f254691f481694347de35ca7b",
          "sha256": "b07895862f7cd2512012946efb3b37d21f833c561032734555dcebbc141f6f41",
          "sha1": "d0b85c61fac1b284afb6be710bb1dbf1ed247594",
          "md5": "68475e73a92c62445515c1d64180443e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "noderesolver-0.1.0-alpha.4-sources.jar",
          "url": "noderesolver-0.1.0-alpha.4-sources.jar",
          "size": 1705,
          "sha512": "d2322ab9c2e97ee829773f543afd2005e1619db142a97e15ad034c4c1191632a1fba1daa6e771f37b0aa15f3915d2696c7d2ad25140c2bcb751de230f07691f6",
          "sha256": "881351360112287a3f48aa3d5eab7d37aa90d045df58cf486f8fc7f86248d6a8",
          "sha1": "066288ca0653f75ff7d767d2b91c0a0cb854c1a2",
          "md5": "840a84a3dd8dc24569fc7c75a936d5bb"
        }
      ]
    }
  ]
}
